### ISSUE TITLE
Expose ports only to a private network

### ISSUE THREAD

**Issue by qulo** [mxschmitt/ui-driver-hetzner#43] opened 2019-07-17 12:07 UTC
Currently, when you use the new networks feature, all ports are exposed on both interfaces. So when you do a nmap on the public ip and the private ip, you get the same result: 
```
PORT      STATE SERVICE
22/tcp    open  ssh
80/tcp    open  http
443/tcp   open  https
2376/tcp  open  docker
2379/tcp  open  unknown
2380/tcp  open  unknown
6443/tcp  open  unknown
8181/tcp  open  unknown
10250/tcp open  unknown
10251/tcp open  unknown
10252/tcp open  unknown
10254/tcp open  unknown
10257/tcp open  unknown
10259/tcp open  unknown
18080/tcp open  unknown
```
(I didn't scan for open udp ports)

The docker service simply binds to `0.0.0.0`
It would be nice to optionally bind all the K8s ports only to the internal network IP (Hetzner default is 10.0.0.0/16), so that they are not exposed to the internet any more. Is this possible?

**Comment by mxschmitt** [comment] 2019-07-23 11:54
Maybe related to #44. But not sure. I don't see any option in Rancher to prevent this. Is this also reproducible in e.g. the DigialOcean Rancher/Docker driver?

**Comment by mxschmitt** [comment] 2019-08-02 12:18
Closing, because of duplicate of #44. Have to investigate, I will try with Digital Ocean.

**Closed by mxschmitt** 2019-08-02 12:18 UTC

**Comment by vitobotta** [comment] 2020-01-09 21:25
Hi @mxschmitt have you had a chance to check this with DigitalOcean?

**Comment by mxschmitt** [comment] 2020-01-13 16:02
@vitobotta afaik the same issue is persistent on Digital Ocean. But it's quite a long time ago, so not sure.

**Comment by vitobotta** [comment] 2020-01-13 16:47
Hi @mxschmitt yeah I tried it in the meantime and it's the same problem. I am back to using custom nodes now because of this :(

**Comment by mxschmitt** [comment] 2020-02-10 10:15
For other users which run into the problem: https://github.com/vitobotta/hetzner-cloud-init by @vitobotta might help. :) thx!

**Comment by vitobotta** [comment] 2020-02-10 13:38
Thanks @mxschmitt ! 😄
