### ISSUE TITLE
Ubuntu 18.04 provisioning not working due broken apt sources.list

### ISSUE THREAD

**Issue by dneckel** [mxschmitt/ui-driver-hetzner#34] opened 2019-04-24 10:19 UTC
Some days ago everything was working fine but starting today I am no longer able to provision a new cluster.

The error I run into is this:
"Error creating machine: Error running provisioning: Error running "sudo apt-get update": ssh command error:"

Maybe the driver is colliding with the cloud-init that is run by Hetzner itself?

**Comment by mxschmitt** [comment] 2019-04-24 10:32
Please provide me all your details, which you have selected in your driver dialog on Rancher (os, docker version, image). Without that I can't assist you. :)

**Comment by dneckel** [comment] 2019-04-24 10:37
Node Template Settings

Region: Nuremberg
Image: Ubuntu 18.04
Size: CX31 - 8GB Memory - 80GB Disk space
Docker Install URL: https://releases.rancher.com/install-docker/18.09.sh

Other than those nothing special.

**Comment by mxschmitt** [comment] 2019-04-24 10:57
Hi,
thanks for the response. I could reproduce it.
It's due Hetzner Cloud currently deliver in their `Ubuntu 18.04` image a "broken apt source list".
You can reproduce it when you create a `Ubuntu 18.04` machine directly in the Hetzner Cloud console, connect and check the output of the "apt update" command.
```
Err:9 http://mirror.hetzner.de/ubuntu/packages bionic/main amd64 Packages        
  404  Not Found [IP: 213.133.99.97 80]
```
cc @thcyron @thetechnick @LKaemmerling

**Comment by LKaemmerling** [comment] 2019-04-24 11:31
Hey,

we have currently an issue with the mirror. You can find the Hetzner Status Entry for this here:
https://www.hetzner-status.de/#11493

**Comment by mxschmitt** [comment] 2019-04-25 06:02
I will close this issue here, because it's fixed from Hetzner Cloud side. Thanks to @LKaemmerling :)

**Closed by mxschmitt** 2019-04-25 06:02 UTC

**Comment by tonnenpinguin** [comment] 2019-05-29 14:50
I'm still experiencing this issue. Is everything back to normal for you guys?

I am using the same config as @dneckel

**Comment by phvreeuwijk** [comment] 2019-05-29 15:14
I'm experiencing this as well: 
```
Get:20 http://mirror.hetzner.de/ubuntu/packages bionic-updates/universe amd64 Packages [943 kB]
Err:20 http://mirror.hetzner.de/ubuntu/packages bionic-updates/universe amd64 Packages
  
Fetched 88.7 kB in 1s (92.4 kB/s)                          
Reading package lists... Done
E: Failed to fetch http://mirror.hetzner.de/ubuntu/packages/dists/bionic-updates/universe/binary-i386/Packages.xz  File has unexpected size (930824 != 930836). Mirror sync in progress? [IP: 2a01:4f8:0:1::1:97 80]
   Hashes of expected file:
    - Filesize:930836 [weak]
    - SHA256:490ca13e8e53ffa43ae824baf4a8052c10f80e0280e9e95201760c9ffa3fba81
    - SHA1:c66df72b864e2a09017ba6749d9e5d62f93cb339 [weak]
    - MD5Sum:fb848b9e7e0e0c25a96499ef876498f6 [weak]
   Release file created at: Wed, 29 May 2019 12:50:48 +0000
E: Failed to fetch http://mirror.hetzner.de/ubuntu/packages/dists/bionic-updates/universe/binary-amd64/Packages.xz  
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by mxschmitt** [comment] 2019-05-29 16:01
Unfortunately this is a Hetzner related issue :/
