### ISSUE TITLE
Automatic firewall setup and config during cluster creation

### ISSUE THREAD

**Issue by anebi** [mxschmitt/ui-driver-hetzner#61] opened 2019-10-21 17:34 UTC
Hello,

I would like to request a new feature that I think would be great and really useful. and I guess it can be done automatically from this driver. You know when a new cluster is created, then driver creates the cloud instances and setup everything necessary. Once the setup is completed we can go and check on cloud instances and we will notice that nodes are actually not protected with firewall. Firewall is inactive. I know that we can create rules through user data config, but it would be best if driver sets the firewall rules (sets all required inbound/outbound ports) automatically.

As far as i rembeber if we setup cluster using Amazon EKS, all firewall stuff on amazon is set automatically. It would be great if we have something with this driver too using nodes firewalls (iptables, ufw,firewalld or whatever is used).

Let me know what you think about this idea or how you do this on your clusters.

Thank you in advance!

Best regards,
Ali Nebi

**Comment by mxschmitt** [comment] 2020-02-22 12:23
Duplicate of #79 

https://github.com/vitobotta/hetzner-cloud-init is a tool (by @vitobotta) which fixes this issue.

**Closed by mxschmitt** 2020-02-22 12:23 UTC
